### ISSUE TITLE
Old commands in /thelp

### ISSUE THREAD

**Issue by PatchwerkQWER** [Pottus/Texture-Studio#10]
Hi,

there are same old (doesn't exist) commands like /setindex and there are missing new commands like /showtext3d /hidetext3d

**Comment by Crayder** [comment]
Actually there are a few more commands missing from `thelp`. 

I'll concatenate all of the files and extract the cmds, easiest way.

**Comment by PatchwerkQWER** [comment]
Much better. BTW you will update the tstudio amx file? I don't have problem compile it but it's useful when I doesn't need compile it.

**Comment by Crayder** [comment]
Yea, I was actually compiling before you commented. I came across some things I needed to fix because I was using my local YSI4.
