### ISSUE TITLE
Texture-Studio streamer problem

### ISSUE THREAD

**Issue by akib2002** [Pottus/Texture-Studio#100]
Whenever I try to open my samp server console, it displays this message
`Streamer Plugin: Streamer_SetVisibleItems: Expecting 3 parameter(s), but found 2`

I have latest streamer plugin, 
I was having issues with the streamer plugin that was inside of Texture-studio.zip (Failed to load)
So I used latest plugin and this problem spikes.

When I try to create object it displays this message on my console
`[00:44:49] *** Streamer Plugin: CreateDynamicObject: Expecting 14 parameter(s), but found 12.
[00:44:49] *** Streamer Plugin: Streamer_SetFloatData: Invalid ID specified.
[00:44:49] *** Streamer Plugin: Streamer_Update: Expecting 2 parameter(s), but found 1.
[00:44:49] *** Streamer Plugin: CreateDynamic3DTextLabel: Expecting 15 parameter(s), but found 13.
[00:44:49] *** Streamer Plugin: Streamer_Update: Expecting 2 parameter(s), but found 1.`

**Comment by Crayder** [comment]
Well, your problem is that you're using the latest version of streamer. As noted on the forum and on here, you must use the files that come with the package. There are compatibility issues that have not been resolved yet.

**Comment by akib2002** [comment]
Then how i can solve `Failed to load plugin`

**Comment by akib2002** [comment]
I wanted to share my experience how I fixed this problem,

http://www.microsoft.com/en-us/download/details.aspx?id=5555
http://www.microsoft.com/en-us/download/details.aspx?id=8328
http://www.microsoft.com/en-us/download/details.aspx?id=30679
https://www.microsoft.com/en-us/download/details.aspx?id=48145

I just downloaded and installed them, now it's working fine. 

After much time later now I can use texture studion again <3

**Comment by Crayder** [comment]
Again, if you just look at the forum or this front page, it tells you to do that.

**Comment by MuhammedAnzil7** [comment]
----------
Loaded log file: "server_log.txt".
----------

SA-MP Dedicated Server
----------------------
v0.3.7-R2, (C)2005-2015 SA-MP Team


Server Plugins
--------------
 Loading plugin: crashdetect
  Failed.
 Loading plugin: sscanf
  Failed.
 Loading plugin: streamer
  Failed.
 Loading plugin: filemanager
******************
** FILE MANAGER **
**    Loaded    **
** Version 1.5 **
******************
  Loaded.
 Loaded 1 plugins.


Started server on port: 7777, with maxplayers: 10 lanmode is OFF.


Filterscripts
---------------
  Loading filterscript 'tstudio.amx'...
  Loading filterscript 'fsdebug.amx'...

  *********************
  * SA:MP DEBUG 0.2   *
  * By Simon Campbell *
  *********************
  * Version: 0.5d      *
  *********************
  * -- LOADED         *
  *********************

  Loaded 2 filterscripts.

Script[gamemodes/bare.amx]: Run time error 19: "File or function is not found"
Number of vehicle models: 0
