### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by DragonCobra11Max** [Pottus/Texture-Studio#107]
when i open and compile tsmain.pwn there is 16 errors, where i can change commands from "cobject" to shorter "oc " and if anyone can help me how to do shortcut command in ycmd...thanks

**Comment by DragonCobra11Max** [comment]
okay in tsmain i done #include  <a_samp> on top and now remains only 10 errors about db. files
C:\Users\diyyo\Desktop\SAMP MapForce Server\filterscripts\tstudio\tsmain.pwn(12) : error 017: undefined symbol "SystemDB"
C:\Users\diyyo\Desktop\SAMP MapForce Server\filterscripts\tstudio\tsmain.pwn(12) : error 017: undefined symbol "db_open_persistent"
C:\Users\diyyo\Desktop\SAMP MapForce Server\filterscripts\tstudio\tsmain.pwn(13) : error 017: undefined symbol "ThemeDataDB"
C:\Users\diyyo\Desktop\SAMP MapForce Server\filterscripts\tstudio\tsmain.pwn(13) : error 017: undefined symbol "db_open_persistent"
C:\Users\diyyo\Desktop\SAMP MapForce Server\filterscripts\tstudio\tsmain.pwn(14) : error 017: undefined symbol "sqlite_ThemeSetup"
C:\Users\diyyo\Desktop\SAMP MapForce Server\filterscripts\tstudio\tsmain.pwn(15) : error 017: undefined symbol "sqlite_LoadBindString"
C:\Users\diyyo\Desktop\SAMP MapForce Server\filterscripts\tstudio\tsmain.pwn(31) : error 017: undefined symbol "foreach"
C:\Users\diyyo\Desktop\SAMP MapForce Server\filterscripts\tstudio\tsmain.pwn(31) : error 029: invalid expression, assumed zero
C:\Users\diyyo\Desktop\SAMP MapForce Server\filterscripts\tstudio\tsmain.pwn(31) : error 017: undefined symbol "i"
C:\Users\diyyo\Desktop\SAMP MapForce Server\filterscripts\tstudio\tsmain.pwn(31) : fatal error 107: too many error messages on one line

Compilation aborted.Pawn compiler 3.2.3664	 	 	Copyright (c) 1997-2006, ITB CompuPhase

**Comment by DragonCobra11Max** [comment]
okay also i have noticed if i try to compile any of the pwn files i get bunch of errors, so basically means that i cant compile it on my pc i have to use your amx file to make it work..

**Comment by Crayder** [comment]
You are trying to compile the modular scripts. Instead you must compile `tstudio.pwn`.

In regards to making additional commands, first keep in mind this uses legacy YSI so syntax is not like YSI 4 or YSI 5. Look for YSI 3.1 documentation. [See this](https://forum.sa-mp.com/showthread.php?t=571047). `Command_AddAltNamed("help", "aiuto");`
