### ISSUE TITLE
/gaexport

### ISSUE THREAD

**Issue by Crayder** [Pottus/Texture-Studio#11]
Complete the /gaexport command.

**Comment by Crayder** [comment]
@Pottus What exactly is wrong with this? You have it commented out, and I haven't tried commenting it yet.

**Comment by Pottus** [comment]
It was never completed the intention is to export a group of objects attached to a golf ball located at the group centre.

**Comment by Crayder** [comment]
Oh, I edited it a while back, I didn't have the commit in it's own commit though.

https://github.com/Pottus/Texture-Studio/commit/85a83e34f6fc0a828bb665803ab7a57bb30a0b27

I forgot where I was going with it. It looks good so I guess I'll just have to test it.

**Comment by Crayder** [comment]
Ok, so the current code (from the commit mentioned above) crashes after entering the parent object. It's the first fwrite line after fopen so it's a file crash. I tried using ftouch and io_append to get past it, neither worked. The file is never created.

**Comment by Pottus** [comment]
Maybe the folder does not exist.

**Comment by Pottus** [comment]
One more thing this line here.
format(templine,sizeof(templine),"centobjid = CreateObject(%i,%.3f,%.3f,%.3f,%.3f,%.3f,%.3f,%.3f);\r\n",ObjectData[centerindex][oModel],ObjectData[centerindex][oX],ObjectData[centerindex][oY],ObjectData[centerindex][oZ],ObjectData[centerindex][oRX],ObjectData[centerindex][oRY],ObjectData[centerindex][oRZ],drawdist);

The center object should be a golf ball with it's material colour set so that it is invisible. That means a centerindex shouldn't be choose but get the group center instead.

**Comment by Crayder** [comment]
- Maybe the folder does not exist.

It does, I even have it created here in this repo. It contains a blank text file.

- The center object should be a golf ball with it's material colour set so that it is invisible. That means a centerindex shouldn't be used get the group center instead.

I like the idea of choosing an object to be the parent instead. There are a few good reasons. One great one would be considering the fact that the physical center is not always the best center of rotation. For example, what if I made my own door or something and the parent object should be the hinge? A golf ball in the center wouldn't work for that scenario. I could easily default it to a golf ball at the center though, that would make sense with a note [like in the draw distance dialog] saying that if nothing is entered it will default to the center. Your opinion on that?

**Comment by Crayder** [comment]
Okay so this is done and implemented for public use. But it still doesn't create the file, no matter what I try to do. The folder is perfectly valid and all other file operations work perfectly fine. I don't get it!

**Comment by Crayder** [comment]
I'm going to go ahead and close this issue, it's technically working but without the actual new file.

@Pottus if you could look into the file creating that'd be great, I really don't see what I could possibly be doing wrong. It's probably something minor that I'm just not noticing.
