### ISSUE TITLE
/mtextures and /tsearch

### ISSUE THREAD

**Issue by DragonCobra11M** [Pottus/Texture-Studio#113]
When I do /mtextures it display all textures in pictures, but /tsearch where i can input name of texture showing me only names of texture, so what i need and will help others is /tsearch <name of texture with /mtexture  style of listing. Also adding actors in this nice work would be crown on top.. Keep it up

**Comment by Crayder** [comment]
This is already a thing sir; /mtsearch
"Same as /tsearch, but in the 3D texture viewer."

Perhaps you should take a look at /thelp!
