### ISSUE TITLE
AMX Backtrace: "Heap underflow"

### ISSUE THREAD

**Issue by GroWyAdv** [Pottus/Texture-Studio#120]
Hi, i tried a few times to use the latest version but i always have this problem and the server doesn't work.

```
[debug] AMX backtrace:
[debug] Run time error 8: "Heap underflow"
[debug]  Heap pointer (HEA) is 0x2885C30, heap bottom (HLW) is 0x2BF8B5C
```

The commands don't work, `SERVER: Unknown command.`!

**Comment by GroWyAdv** [comment]
The problem was solved after i updated YSI includes to YSI 4, updated plugins: sscanf, streamer and crashdetect, updated include sqlitei.

**Comment by AnthonyJuan** [comment]
oi, poderia me ajudar a resolver esse problema?
