### ISSUE TITLE
Problem with command /gtaobjects

### ISSUE THREAD

**Issue by SkolPlay** [Pottus/Texture-Studio#123]
Hi!

Recently, I was using texture studio and I noticed a problem, it is the following, in the / gtaobjects command, it is accusing a problem, when I type the same I am unable to type something in the chat or even another command, not to mention that it does not it works.

**Comment by Crayder** [comment]
The server will freeze when TStudio begins applying changes to thousands of objects. This is a limitation of using pawn lang and the plugins. After a few moments, the server will unfreeze and continue normal operation.

Also, it does work, as explained above it'll just take a moment. Have you tried giving it some time?

**Comment by SkolPlay** [comment]
No, you will take a break and then return.

**Comment by SkolPlay** [comment]
That's right, I had to wait a while. pardon me
