### ISSUE TITLE
Run time error 8: "Heap underflow"

### ISSUE THREAD

**Issue by KirovYuri** [Pottus/Texture-Studio#134]
i have an error here

`[join] Kirov_Yuri has joined the server (0:127.0.0.1)
[debug] Run time error 8: "Heap underflow"
[debug]  Heap pointer (HEA) is 0x1, heap bottom (HLW) is 0x2BF8B5C
[debug] AMX backtrace:
[debug] Run time error 8: "Heap underflow"
[debug]  Heap pointer (HEA) is 0x1, heap bottom (HLW) is 0x2BF8B5C
[debug] AMX backtrace:
[debug] Run time error 8: "Heap underflow"
[debug]  Heap pointer (HEA) is 0x1, heap bottom (HLW) is 0x2BF8B5C
[debug] AMX backtrace:
[debug] Run time error 8: "Heap underflow"
[debug]  Heap pointer (HEA) is 0x1, heap bottom (HLW) is 0x2BF8B5C
[debug] AMX backtrace:
[debug] Run time error 8: "Heap underflow"
[debug]  Heap pointer (HEA) is 0x1, heap bottom (HLW) is 0x2BF8B5C
[debug] AMX backtrace:
[debug] Run time error 8: "Heap underflow"
[debug]  Heap pointer (HEA) is 0x1, heap bottom (HLW) is 0x2BF8B5C
[debug] AMX backtrace:
[debug] Run time error 8: "Heap underflow"
[debug]  Heap pointer (HEA) is 0x1, heap bottom (HLW) is 0x2BF8B5C
[debug] AMX backtrace:
[debug] Run time error 8: "Heap underflow"
[debug]  Heap pointer (HEA) is 0x1, heap bottom (HLW) is 0x2BF8B5C
[debug] AMX backtrace:
[debug] Run time error 8: "Heap underflow"
[debug]  Heap pointer (HEA) is 0x1, heap bottom (HLW) is 0x2BF8B5C
[debug] AMX backtrace:
[debug] Run time error 8: "Heap underflow"
[debug]  Heap pointer (HEA) is 0x1, heap bottom (HLW) is 0x2BF8B5C
[debug] AMX backtrace:
[debug] Run time error 8: "Heap underflow"
[debug]  Heap pointer (HEA) is 0x1, heap bottom (HLW) is 0x2BF8B5C
[debug] AMX backtrace:
[debug] Run time error 8: "Heap underflow"
[debug]  Heap pointer (HEA) is 0x1, heap bottom (HLW) is 0x2BF8B5C
[debug] AMX backtrace:
[debug] Run time error 8: "Heap underflow"
[debug]  Heap pointer (HEA) is 0x1, heap bottom (HLW) is 0x2BF8B5C
[debug] AMX backtrace:
[debug] Run time error 8: "Heap underflow"
[debug]  Heap pointer (HEA) is 0x1, heap bottom (HLW) is 0x2BF8B5C
[debug] AMX backtrace:
[debug] Run time error 8: "Heap underflow"
[debug]  Heap pointer (HEA) is 0x1, heap bottom (HLW) is 0x2BF8B5C
[debug] AMX backtrace:
[debug] Run time error 8: "Heap underflow"
[debug]  Heap pointer (HEA) is 0x1, heap bottom (HLW) is 0x2BF8B5C
[debug] AMX backtrace:
[debug] Run time error 8: "Heap underflow"
[debug]  Heap pointer (HEA) is 0x1, heap bottom (HLW) is 0x2BF8B5C
[debug] AMX backtrace:
[debug] Run time error 8: "Heap underflow"
[debug]  Heap pointer (HEA) is 0x1, heap bottom (HLW) is 0x2BF8B5C
[debug] AMX backtrace:
[debug] Run time error 8: "Heap underflow"
[debug]  Heap pointer (HEA) is 0x1, heap bottom (HLW) is 0x2BF8B5C
[debug] AMX backtrace:
[debug] Run time error 8: "Heap underflow"
[debug]  Heap pointer (HEA) is 0x1, heap bottom (HLW) is 0x2BF8B5C
[debug] AMX backtrace:
[debug] Run time error 8: "Heap underflow"
[debug]  Heap pointer (HEA) is 0x1, heap bottom (HLW) is 0x2BF8B5C
[debug] AMX backtrace:
[debug] Run time error 8: "Heap underflow"
[debug]  Heap pointer (HEA) is 0x1, heap bottom (HLW) is 0x2BF8B5C
[debug] AMX backtrace:
[debug] Run time error 8: "Heap underflow"
[debug]  Heap pointer (HEA) is 0x1, heap bottom (HLW) is 0x2BF8B5C
[debug] AMX backtrace:
[debug] Run time error 8: "Heap underflow"
[debug]  Heap pointer (HEA) is 0x21, heap bottom (HLW) is 0x2BF8B5C
[debug] AMX backtrace:
[debug] Run time error 8: "Heap underflow"
[debug]  Heap pointer (HEA) is 0x1, heap bottom (HLW) is 0x2BF8B5C
[debug] AMX backtrace:
[debug] Run time error 8: "Heap underflow"
[debug]  Heap pointer (HEA) is 0x1, heap bottom (HLW) is 0x2BF8B5C
[debug] AMX backtrace:
[debug] Run time error 8: "Heap underflow"
[debug]  Heap pointer (HEA) is 0x1, heap bottom (HLW) is 0x2BF8B5C
[debug] AMX backtrace:
[debug] Run time error 8: "Heap underflow"
[debug]  Heap pointer (HEA) is 0x1, heap bottom (HLW) is 0x2BF8B5C
[debug] AMX backtrace:
[debug] Run time error 8: "Heap underflow"
[debug]  Heap pointer (HEA) is 0x1, heap bottom (HLW) is 0x2BF8B5C
[debug] AMX backtrace:
[debug] Run time error 8: "Heap underflow"
[debug]  Heap pointer (HEA) is 0x1, heap bottom (HLW) is 0x2BF8B5C
[debug] AMX backtrace:
[debug] Run time error 8: "Heap underflow"
[debug]  Heap pointer (HEA) is 0x1, heap bottom (HLW) is 0x2BF8B5C
[debug] AMX backtrace:
[debug] Run time error 8: "Heap underflow"
[debug]  Heap pointer (HEA) is 0x1, heap bottom (HLW) is 0x2BF8B5C
[debug] AMX backtrace:
[debug] Run time error 8: "Heap underflow"
[debug]  Heap pointer (HEA) is 0x1, heap bottom (HLW) is 0x2BF8B5C
[debug] AMX backtrace:
[debug] Run time error 8: "Heap underflow"
[debug]  Heap pointer (HEA) is 0x1, heap bottom (HLW) is 0x2BF8B5C
[debug] AMX backtrace:
[debug] Run time error 8: "Heap underflow"
[debug]  Heap pointer (HEA) is 0x1, heap bottom (HLW) is 0x2BF8B5C
[debug] AMX backtrace:
[debug] Run time error 8: "Heap underflow"
[debug]  Heap pointer (HEA) is 0x1, heap bottom (HLW) is 0x2BF8B5C
[debug] AMX backtrace:
[debug] Run time error 8: "Heap underflow"
[debug]  Heap pointer (HEA) is 0x1D, heap bottom (HLW) is 0x2BF8B5C
[debug] AMX backtrace:
[debug] Run time error 8: "Heap underflow"
[debug]  Heap pointer (HEA) is 0x1, heap bottom (HLW) is 0x2BF8B5C
[debug] AMX backtrace:
`

can you fix this??

**Comment by RodrigoMSR** [comment]
Put this tstudio.amx in filterscripts: [tstudio.zip](https://github.com/Pottus/Texture-Studio/files/11410909/tstudio.zip)

I compiled using updated compiler and YSI, plus I set "FORMAT_REPLACE_NATIVES" to false in formatex.inc.

**Comment by KirovYuri** [comment]
> Put this tstudio.amx in filterscripts: [tstudio.zip](https://github.com/Pottus/Texture-Studio/files/11410909/tstudio.zip)
> 
> I compiled using updated compiler and YSI, plus I set "FORMAT_REPLACE_NATIVES" to false in formatex.inc.

thanks its working

**Comment by suhailAju** [comment]
than

> Put this tstudio.amx in filterscripts: [tstudio.zip](https://github.com/Pottus/Texture-Studio/files/11410909/tstudio.zip)
> 
> I compiled using updated compiler and YSI, plus I set "FORMAT_REPLACE_NATIVES" to false in formatex.inc.

thank you bro it is working
