### ISSUE TITLE
Add RZ to Objectometry orientation.

### ISSUE THREAD

**Issue by Crayder** [Pottus/Texture-Studio#14]
I've had a lot of problems with the Z rotation not being included in the OBM orientation. I noticed how important it was when I couldn't rotate an object the way I wanted it to be using X and Y. I thought it was just me so I never thought it was much use to anyone else, then today someone asked about it and I decided to update it.

I plan on having 1.8 be a larger update so I'll add it to the 1.8 milestone.

**Comment by Crayder** [comment]
@Pottus I'm having trouble with the "Set Rotation Orientation" with this. Everything else is fine, but the editing mode is behaving strangely. Perhaps you could come on TV or something? If so I'll connect on Mumble so I can send you the information.

**Comment by Crayder** [comment]
(closed the wrong issue)

**Comment by Pottus** [comment]
I would have to take a look at it I am sure there is a reason I did this.

**Comment by Crayder** [comment]
Should I send you the code I have? It's be easier if you could connect on team viewer.

**Comment by Crayder** [comment]
Actually, it seems to be working now. I'm not really sure what I did to fix it.
