### ISSUE TITLE
Per-Object/Group Draw Distance

### ISSUE THREAD

**Issue by Crayder** [Pottus/Texture-Studio#16]
This is relatively simple.

Commands: `/odd` and `/gdd`

@ipsLeon, any further recommendations on this?

**Comment by ipsLeon** [comment]
Yeah, one more suggestion is make it in a range of objects, for example /odd <Float:drawdistance> <objectindex/startindex> <endindex(optional)>, or simply create a /godd to adjust the drawdistance of a certain group of objects =]

**Comment by Crayder** [comment]
Your `/godd` is what my `/gdd` is above, precisely.

**Comment by ipsLeon** [comment]
Nice, keep it up =]

**Comment by PT-Player** [comment]
I really like what are you doing @Crayder 

Nice work bro!
