### ISSUE TITLE
Temporary vehicles

### ISSUE THREAD

**Issue by Crayder** [Pottus/Texture-Studio#17]
Regarding a suggestion by ipsLeon (aka. n0minal, right?), which was the ability to destroy vehicles created by the fsdebug filterscript, I will just add a temporary vehicle system to replace that.

It may just be a simple command that will create a vehicle facing the direction you are, put you in it, and automatically destroy it once you exit. @ipsLeon give me your opinion on this take.

Maybe `/tcar`?

**Comment by ipsLeon** [comment]
Nice, will come in handy, /tcar is a nice name for a CMD and yes I'm n0minal :)

**Comment by Crayder** [comment]
OK, good. I plan on doing more in the next month or so because I have a bit of free time.
