### ISSUE TITLE
Administrator Lock

### ISSUE THREAD

**Issue by Crayder** [Pottus/Texture-Studio#18]
Some kind of personal lock, so others that are online can't edit. When an RCON (this won't have a user system) `/lock`'s editing only he/she will be able to edit anything.

**Comment by JustMe77** [comment]
Nice idea. I don't know if this is in your idea included, if not it should:

/renamemap & /deletemap should also only be able to use if you're an "Administrator".

And add also a command to give someone tempacces to use the commands.
