### ISSUE TITLE
Use allbuildings.db instead of the extreme array.

### ISSUE THREAD

**Issue by Crayder** [Pottus/Texture-Studio#19]
I uploaded the database in 85a83e34f6fc0a828bb665803ab7a57bb30a0b27. That commit was actually supposed to be two separate commits but I combined them (without realizing it at first), but it's fine.

**Comment by Pottus** [comment]
Good idea this is really a bottleneck in the compile time.

**Comment by Crayder** [comment]
Yeah this and modelsizes are a big part.

I made this to cover the modelsizes already: https://github.com/Crayder/Model-Sizes-Plus/tree/db-mode
