### ISSUE TITLE
Per object draw distance and object notes.

### ISSUE THREAD

**Issue by JustMe77** [Pottus/Texture-Studio#22]
-Command to change the Draw Distance of the whole Map.
It's really a huge work to change every object's stream distance from 300 to another one if you got more than 100 objects.

-Command to change the Draw Distance of a specific Object.
Will be very useful. It's ultra annoying to search in the Script an object you want to stream more than 300 meters, and this will become very shitty when you got that object more than 100 times.

-Command to comment a specific Object
Useful for many things.

-Command to delete Prefabs.
Useful to keep the list clean and also cool that it's possible ingame.

-Command to rename Prefabs.
Not very necessary but could be useful and shouldn't be hard since you also managed to create a command to change Mapnames.

**Comment by Crayder** [comment]
-Command to change the Draw Distance of the whole Map.
	It's really a huge work to change every object's stream distance from 300 to another one if you got more than 100 objects.
	
	-Command to change the Draw Distance of a specific Object.
	Will be very useful. It's ultra annoying to search in the Script an object you want to stream more than 300 meters, and this will become very shitty when you got that object more than 100 times.

This is already being done. This is like the 20th time you suggested it.

	-Command to comment a specific Object
	Useful for many things.

I was actually considering adding a 'note' feature that would use 3D text and would not be exported. Not sure what you meant by comment though. Like, a comment that could be read with a command or something? If you mean like 3D text I might even consider that because it wouldn't be to hard.

	-Command to delete Prefabs.
	Useful to keep the list clean and also cool that it's possible ingame.
	
	-Command to rename Prefabs.
	Not very necessary but could be useful and shouldn't be hard since you also managed to create a command to change Mapnames.

Yes, it can be done. But it's not near as important as map names were. I might do it when I get bored and have free time.

**Comment by JustMe77** [comment]
1) This is already being done. This is like the 20th time you suggested it.
Since when it's done and this is the first time I am suggesting it. I am not talking about the draw distance of the 3D Text which got already accepted and is done. I am talking about the Draw Distance of the Objects.  I want to stream for example a few Objects more than 300 m which is the default amount, but the problem is those Objects exist more than 100 times in my Map and it's really messy to go through the whole Mapping Code and check which of the 100 Objects is the right one so I can increase the stream distance.

I was actually considering adding a 'note' feature that would use 3D text and would not be exported. Not sure what you meant by comment though. Like, a comment that could be read with a command or something? If you mean like 3D text I might even consider that because it wouldn't be to hard.

I'm not talking about a 3D Text. I mean a command with which you can add a comment, and when you export later the Object you can see your note. 
Example: tmpobjid = CreateObject(19377,-151.725,1219.495,18.233,0.000,0.000,0.000,300.000) //YOUR COMMENT.

And 3rd

Yes, it can be done. But it's not near as important as map names were. I might do it when I get bored and have free time.

I agree it's not very important but if you have time you could do this, I can wait for this since it's not very necessary :D

Peace

**Comment by Crayder** [comment]
`Since when it's done and this is the first time I am suggesting it. `
http://forum.sa-mp.com/showthread.php?p=3598741

**Comment by JustMe77** [comment]
Okay 1:0 for you. But "This is like the 20th time you suggested it." is also not true :P 1:1

And yea, I suggested it but it is finished yet or just in the ToDo List?

**Comment by Crayder** [comment]
It's in the to-do list.

**Comment by JustMe77** [comment]
When it'll be done, Craider?

**Comment by Crayder** [comment]
- [ ] Per-Object Draw Distance: Set view distance of an object by the players current distance from the object or by input. Also exported with higher priority than the default draw distance.
- [ ] Object Notes: A, let's say 48, character string saved with objects. Also exported as pawn comments with map exports.

Expected completion time not projectable at the moment, but let's say I'll try to get to it soon.

Setting to the Before 1.9 milestone.

**Comment by Crayder** [comment]
Object notes part complete, with Text3D and export comments.

Only in the inprogress branch until I release 1.9!
