### ISSUE TITLE
/avclonecar "Bug"

### ISSUE THREAD

**Issue by JustMe77** [Pottus/Texture-Studio#24]
Yo, it ain't really a bug, but it clones everything except car colors and maybe (not tested) car tuning too.

Easy to fix, do it in the next version :P

**Comment by Crayder** [comment]
"do it in the next version"

Don't command me... D`:

**Comment by JustMe77** [comment]
Hehe, ty.

**Comment by Crayder** [comment]
I added tuning, color, and paint jobs.

I'll test it later:
