### ISSUE TITLE
Map Settings Table

### ISSUE THREAD

**Issue by JustMe77** [Pottus/Texture-Studio#26]
Yo, small suggestion rather than using always /ogoto to go to the Map. You can set a specific Spawn on every Map and you can teleport to it without beeing in flymode using /mgoto (/mapgoto)

**Comment by Crayder** [comment]
I'm going to add a new table to the map databases. It'll tell TS what version it was created in and give other useful information.

Some things it will include:
- TS Version
- Date and time last edited
- Spawn position (if a map has one, a message will be shown when the map is loaded to notify)
- Author (player name that did /newmap)

**Comment by Crayder** [comment]
See https://github.com/Pottus/Texture-Studio/commit/dabda67c9a7b494530c0c95a8c1f71ac03971559#commitcomment-18792584
