### ISSUE TITLE
New Vehicle Command

### ISSUE THREAD

**Issue by JustMe77** [Pottus/Texture-Studio#27]
Yo, would be very cool if we would be able to add and remove again the Sirene Sound which got added in 0.3.7.

**Comment by Crayder** [comment]
If you havent noticed I was holding off all database updates for 1.9, this is one of them. Doing this later on today, this is an easy one to do.

**Comment by Crayder** [comment]
Gotta add the siren parameter to all vehicle export lines, add a way to toggle it, and whatever else.
