### ISSUE TITLE
Improve Flymode

### ISSUE THREAD

**Issue by JustMe77** [Pottus/Texture-Studio#28]
Hi, could you add the ability to increase/lower the flymode camera speed? Like in this video

http://forum.sa-mp.com/showthread.php?t=568931 (check 0:20)

Maybe with the + and - Keys.

**Comment by Crayder** [comment]
Perhaps I could make it toggleable. I love the acceleration, but of course there are those of you that like static speeds.

**Comment by JustMe77** [comment]
Yeah right, sometimes it's just necessary to make it very slow when you want to work very accurate, or increase the speed if you wanna go from Place A to Place B ^_^

**Comment by Crayder** [comment]
`if you wanna go from Place A to Place B` just use /setloc. It's a command from fsdebug, the filterscript that comes with SA-MP which is loaded by the default .cfg that comes with TS.

**Comment by JustMe77** [comment]
Yeah I know already about setloc but it is based on coordinates - which is useful but not always. Anyways, I can wait till you added my suggestion, ty.

**Comment by Crayder** [comment]
I'll add three commands, one to set the max speed, one to change the acceleration level, and one to toggle acceleration.

```
/fmspeed
/fmaccel
/fmtoggle
```
