### ISSUE TITLE
/mtcolorall Bug

### ISSUE THREAD

**Issue by JustMe77** [Pottus/Texture-Studio#29]
Yo, I just mapped a Map and put on the Object 18981 the Color 0x00FF0000 with using /mtcolorall. That works fine but when I reload the Map, the Objects are loaded without the color. If I use /mtcolor on every object that bug doesnt appear. Hope you can fix it.

Regards

**Comment by Crayder** [comment]
Well I use it all the time, and I've never noticed this. But I see the problem, I didn't end the transaction.

**Comment by Crayder** [comment]
Let me know if this actually fixes the issue, but it definitely should. You will also notice major speed improvements with these multi-object commands.
