### ISSUE TITLE
Save Group IDs

### ISSUE THREAD

**Issue by JustMe77** [Pottus/Texture-Studio#31]
Hey, I'd like to suggest that Groups you set inside a Map should save and reload after you reload a Map.

Why?

I work a lot with Group IDs and I like to split different objects in groups, so I can work with them better.
Example:

Group 0 - Roof
Group 1 - Floor
Group 2 - Walls

and it's quite annoying that I have to add all objects again when I reload the Map. (After a Map reload the Groups are reset to 0)

**Comment by Crayder** [comment]
Groups are not reset when a map is reloaded.
