### ISSUE TITLE
Remove 'stock' modifier from functions

### ISSUE THREAD

**Issue by Pottus** [Pottus/Texture-Studio#37]
It makes it easier to search during development for the actual function but I always forget to remove it later.

**Comment by Crayder** [comment]
I actually use regular expressions to find all of my functions anyways, I have shortcuts to all of them in AHK for quick use in NPP.

So yeah, this is easy to do and perfectly fine.

Also, once Extreme Studio becomes a bit more usable (it's already in great shape, just a bit more developing to my NPP comfort zone), I'll make TS a project (i.e. Extreme Studio format).

Also 2, I planned on just basically doing a complete reorganization in TS. I was already working on this but there was just so much I got lost in time.

**Comment by Crayder** [comment]
Perhaps keeping a blank macro would be sufficient.

Like, replace all "stock" on functions with "func" and define "func" as nothing?
