### ISSUE TITLE
Clone Building Command

### ISSUE THREAD

**Issue by JustMe77** [Pottus/Texture-Studio#48]
Hi, I'm suggesting a simple command, similar to /swapbuilding with one exception.
It creates the object on the exact position the GTA Object is located at, but it wont delete the GTA Objects.
Useful to clone trees and buildings to keep same height etc..

**Comment by Crayder** [comment]
Bro, this is already done... Please look at /thelp...

**Comment by JustMe77** [comment]
I know already about that command, but I thought the purpose is for something else because I couldn't manage to use it properly. It's not working, do you tested the command?
