### ISSUE TITLE
Flymode is not working after reloading tstudio

### ISSUE THREAD

**Issue by JustMe77** [Pottus/Texture-Studio#49]
Well the title say everything, once I reloadfs tstudio and go into flymode, I can't move with the camera anymore, I can just go in and out of flymode.

**Comment by JustMe77** [comment]
It'll work fine again if you do a relog.

**Comment by Crayder** [comment]
/fmspeed isn't reset correctly, I've already noticed this and plan to fix it.

For now just use "/fmspeed 100" alone to fix the issue.
You can also adjust /fmaccel and /fmtoggle.
