### ISSUE TITLE
Remove a specific object by typing in a radius

### ISSUE THREAD

**Issue by JustMe77** [Pottus/Texture-Studio#53]
I'd suggest a command to remove a specific object with the possibility to put in a range in meters.
Let's say I delete a tree object and put in a range of 500, then all trees with the same object id are going to be removed in a 500m radius range from current position of the player.

Let's say in our example above 100 trees are going to be deleted in a 500m radius. If you'd export now the map, it shouldn't give us 100 RemoveBuilding Lines, it should make it automatically as a loop. You know what I mean

**Comment by Crayder** [comment]
I'm thinking I'll do this in a new separate database table, specifically for range-removed buildings. That'll make things like exporting and importing easier.
