### ISSUE TITLE
RunTime

### ISSUE THREAD

**Issue by bjtower** [Pottus/Texture-Studio#61]
I want to write this program. However, there is a runtime error, and it appears as shown in the picture below. I want to know a solution.[](url)
![runtime](https://user-images.githubusercontent.com/36224645/35906581-6980c9e6-0c2e-11e8-9a47-4003258bb3e3.png)

**Comment by Southclaws** [comment]
[db_get_result_mem_handle](http://wiki.sa-mp.com/wiki/Db_get_result_mem_handle)

> This function was added in SA-MP 0.3.7 R1 and will not work in earlier versions!
