### ISSUE TITLE
Dialogs won't display above default value of entries

### ISSUE THREAD

**Issue by wtfrazr** [Pottus/Texture-Studio#62]
So dialogs don't display entries after the maximum entries for SA:MP dialogs.
/loadmap, /tsearch and other dialogs that could display more but are part of this issue.

I suggest to make the first and last lines "<<Previous Page" & ">>Next Page" buttons leading to continuing dialogs, so all the entries can be displayed.

**Comment by Crayder** [comment]
There isn't a "maximum entries", the only limitation is the dialog string length, which is 4096.
