### ISSUE TITLE
Bring back the old 3dtext behaviour

### ISSUE THREAD

**Issue by wtfrazr** [Pottus/Texture-Studio#63]
When doing /hidetext3d then spawning down an object, it doesn't display the 3dtext for it like it used to do, before 1.9. It is really annoying, when you have a pretty large map with a lot of objects and you wanna get the ID of the said object. Can we revert on this adjustment? Or please make it toggle-able whether I want it to behave the old way or the new way.

**Comment by wtfrazr** [comment]
Thanks! :)

**Comment by Crayder** [comment]
I'm adding it to /edittext3d, toggled off by default.
