### ISSUE TITLE
Minor /gsel issue

### ISSUE THREAD

**Issue by wtfrazr** [Pottus/Texture-Studio#64]
When you use /gsel and you are in /flymode, the information SendClientMessage is giving you the H key to be pressed/held with your LMB to select an object to the group. But in reality, with /flymode the key you need to press/hold the F/Enter key. When walking, the SCM gives the right information, just false for flying.

**Comment by Crayder** [comment]
Ah great point, the information is on here and the forum but it'd obviously be best to note it in TS too... A lot less confusing and it would remind ME the correct flymode controls. The same would apply to the /mtextures command, I could just note the flymode controls there.
