### ISSUE TITLE
Commands to GTA objects do not work.

### ISSUE THREAD

**Issue by bjtower** [Pottus/Texture-Studio#66]
Commands to GTA objects do not work.
The chat log only shows ' GTA Objects Display ' and ' GTA Object Progress ' and can not perform any actions.

**Comment by Crayder** [comment]
I'm using the latest TS right this very moment, and all of the building commands work perfectly fine.

**Comment by wtfrazr** [comment]
Same, they work fine.

**Comment by bjtower** [comment]
The latest TS version and latest SAMP server are in use.
However, the [/ gtaobjects] command is unavailable.
It is written as follows.
Showing GTA Objects or Hiding GTA Objects
