### ISSUE TITLE
/oswap, /skin doesn't work with new IDs

### ISSUE THREAD

**Issue by wtfrazr** [Pottus/Texture-Studio#68]
So basically the new SA:MP 0.3.DL Custom IDs
"Player skins use ranges: 20000 to 30000 (10000 slots)
Objects use negative IDs: -1000 to -30000 (29000 slots)"

Doesn't work inside tstudio.

**Comment by Crayder** [comment]
Actually, it does work. But when 0.3.8 existed the ID's were -2000 to -30000, when DL came out it changed to -1000 to -30000. So currently TS only support the 0.3.8 range but that can easily be fixed.
