### ISSUE TITLE
Object note is too short

### ISSUE THREAD

**Issue by wtfrazr** [Pottus/Texture-Studio#78]
So, I tested out some new features and noticed that using /note, you can only enter two words then the rest you entered doesn't show on the 3dtext.

I have a suggestion for this, because a really long note would be a pain in the ass to display. So just switch from displaying the actual note to display a command, /viewnote when a note is placed on the object.
This would simply display either in the chat or in a simple dialog.

**Comment by wtfrazr** [comment]
https://i.imgur.com/7iTlGop.png

**Comment by Crayder** [comment]
The 3D text labels don't have much room for text. In fact, you see the limit. You can view the rest of the note in /oprop though.
