### ISSUE TITLE
[Enhancement] Raise the max texture reference in /mtset.

### ISSUE THREAD

**Issue by Crayder** [Pottus/Texture-Studio#8]

**Comment by Pottus** [comment]
You can only use 0-15 that is why it is set as it is.

**Comment by Crayder** [comment]
No, not that. The texture reference ID. Right now in your compilation it is 83##, since I added a larger texture list it needs to be raised. I wasn't talking about texture indexes/slots.

**Comment by Pottus** [comment]
Let me look into it sorry I didn't get back sooner.
