### ISSUE TITLE
[BUG] Since the R2 update, I can't go into flymode.

### ISSUE THREAD

**Issue by Crayder** [Pottus/Texture-Studio#9]
Everytime I go into flymode since the update I get that loading screen of death.
![image](https://cloud.githubusercontent.com/assets/9919010/8717815/b6587020-2b6c-11e5-8958-7af9fccf7059.png)
![image](https://cloud.githubusercontent.com/assets/9919010/8717831/d57473be-2b6c-11e5-8acf-c368eeeda608.png)
![image](https://cloud.githubusercontent.com/assets/9919010/8717832/e34196e8-2b6c-11e5-9498-d828a400d292.png)
![image](https://cloud.githubusercontent.com/assets/9919010/8717838/f05b4a2c-2b6c-11e5-80f2-f693871f4cc7.png)

**Comment by Pottus** [comment]
Yeah it's some SA-MP bug happened to me long before.

**Comment by Crayder** [comment]
Yea it has happened to me a lot in the past, but now in R2 it happens every time I go into flymode.
