### ISSUE TITLE
[URGENT]Not Working COMMAND

### ISSUE THREAD

**Issue by DrugDealerss** [Pottus/Texture-Studio#91]
HEY! I'm use 1.9 version 
All command not working, "unkown command error"
PLS HELP

**Comment by DrugDealerss** [comment]
Whatt?

**Comment by Crayder** [comment]
I mean, tell me what you did or something. Everything's working fine for me so it's likely it's just your problem. I'm willing to help but I can't because I'm not experiencing the same issue and you're not explaining anything.

**Comment by DrugDealerss** [comment]
When I write a command, it returns an "unknown command" error.
