### ISSUE TITLE
Impossible to move objects

### ISSUE THREAD

**Issue by dakvital** [Pottus/Texture-Studio#95]
Hi,

I've an issue with Texture Studio.
Indeed, i updated the streamer and i don't have errors in the server_log but when i want to move an object and i save it with the touch ENTER or the touch "F", the object returns to the initial position.
I'm on a Linux Server.

Could you help me ?

Thank you in advance.

Regards.

**Comment by RaphaelCapone** [comment]
I have this problem too when I updated the streamer plugin to the latest version for linux. Try to use the [0.7.2](https://github.com/samp-incognito/samp-streamer-plugin/releases/tag/v2.7.2) version of it.

**Comment by dakvital** [comment]
Thanks, it works !
It's strange like bug...

**Comment by Crayder** [comment]
Yeah, lot's of weird things happen when you try to update things. That's why it says to use the plugins that come with it.
