### ISSUE TITLE
 Why not use textures other than 0-9063?

### ISSUE THREAD

**Issue by khmelev77** [Pottus/Texture-Studio#97]
Hello!
Why not use textures other than 0-9063? 
In this list for example 15991 https://textures.xyin.ws/?page=textures, but texture studio have only 9063.
Maybe I do not understand something?

**Comment by Pottus** [comment]
Not an issue at all and is done purposely! The other textures belong to LOD models in my view these should never be used for texturing so to prevent people who don't know better from using them they were not included and never will be.

**Comment by Crayder** [comment]
Yeah we've just filtered out the lods and stuff. Also SA-MP textures are included!
